version: '3'
services:
  web:
    build: java/.
    restart: always
    ports:
      - "2222:22"
      - "8081:8080"
    links:
      - "db:database"
  db:
    build: postgresql/.
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample